#!/bin/sh

set -x

url='https://archive.ics.uci.edu/static/public/137/reuters+21578+text+categorization+collection.zip'

wget -O dataset.zip "$url"
unzip dataset.zip -d dataset/
tar -xvf dataset/reuters21578.tar.gz -C dataset/
rm dataset.zip
rm dataset/reuters21578.tar.gz
cat dataset/reut2-*.sgm \
    | sed -r \
        -e 's/&[^;]{1,3};//g' \
        -e '1s/^/\<ROOT\>\n/' \
        -e '$a\\</ROOT\>\n' \
        -e 's/<!DOCTYPE[^>]*>//g' \
    | iconv -c -f utf8 -t ascii//TRANSLIT//IGNORE \
    > dataset.sgm
rm -rf dataset/
